# Generated by Django 3.0 on 2022-07-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0002_favorite_brewery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='query',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
