# Generated by Django 3.0 on 2022-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0003_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
