# Generated by Django 3.0 on 2022-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_auto_20220727_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_current_location',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
